### ISSUE TITLE
Complete Client Site navigation

### ISSUE THREAD

**Issue by edat44** [mphelp/tadummy#23]
We need to create our site map for the CLIENT including all relevant pages for different types of users

**Comment by mphelp** [comment]
Clients-side page list:
===============
* Pre-entry point: CAS redirection
* Entry point: Signup 
* Home page ("/")
    * logged in
    * not logged in
* Apply page
* Calendar page
* Report/Contact us

Additional features:
* Status indicator as long tab of TA's for your courses irrelevant of current page
